package com.peacemakers.security

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
	
	/**
	 * Array of controller/action combinations which will be skipped from authentication
	 * if the controller and action names match. The action value can also be '*' if it
	 * encompasses all actions within the controller.
	 */
	static nonAuthenticatedActions = [
			[controller: 'admin', action: '*'],
			[controller: 'school', action: '*']
	]
	
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true
				
				// Determine if the controller/action belongs is not to be authenticated
				def needsAuth = !nonAuthenticatedActions.find {
					//println "${controllerName} - ${actionName} => ${it.controller} - ${it.action}"
					(it.controller == controllerName) &&
							((it.action == '*') || (it.action == actionName))
				}

				if (needsAuth) {
	                // Access control by convention.
	                accessControl()
				}
				// Skip authentication if no auth is needed
				else {
					return true
				}
            }
        }
    }
}
